<?php
/*
Sample program for use with IBM Integration Bus
© Copyright International Business Machines Corporation 2010
Licensed Materials - Property of IBM
*/
class solarUpDown {

	/**
	* A Sample to illustrate how an example Message Flow can be used by a Pattern Author to
	* create different instances of a Message Flow. In this case, the sample will take a 
	* UTC date on an incoming MQ message. It will use a PHP function in a PHP node to calculate 
	* the sunrise and sunset times in UTC, using User Defined Properties (UDPs) for both 
	* latitude and longitude. The latitude and longitude have been specified by the 
	* Pattern Author as Target Properties, so the Pattern User may specify them, when they
	* create a new instance of the Pattern
	*
	* @MessageBrokerCopyTransform
	*/
	
    function evaluate($assembly) {    
		// Retrieve the date value from the incoming XML message
		$dateQuery = $assembly->XMLNSC->sun->dateQuery->getValue();
		
		// Convert the date (UTC) into a timestamp
		$date = strtotime($dateQuery);
		
		// Retrieve the Latitude (degrees) from the 'latitude' User defined property
		$latitude = mb_get_user_defined_property("Latitude");
		
		// Retrieve the Longitude (degrees) from the 'longitude' User defined property
		$longitude = mb_get_user_defined_property("Longitude");
		
		// Generate the sun info available for the supplied date, Latitude & Longitude
		// using the built in PHP function 'date_sun_info' into an array
		$sunInfo = date_sun_info($date,$latitude,$longitude);
		
		// Walk the array of timestamps generated by the function and
		// convert them back into UTC
		foreach ($sunInfo as $key => $sunTimestamp){
			$sunTime[$key] = date('Y-m-d H:i:s e', $sunTimestamp);
			
			//Print data to stdout for the execution group running this Message Flow
			print "\n $key : $sunTimestamp \n";
			print " $key :  $sunTime[$key] \n";
		}
		
		// Output sun data as a sunEvent append to the original XML message
		// See the schema 'solar.xsd'
		$assembly->XMLNSC->sun->sunEventTime = $sunTime;
	    
    }
}
?>